# Generated by Django 4.1.7 on 2023-05-17 14:22

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('gender', models.TextField()),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RESULT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predction', models.TextField(max_length=100)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.registeration')),
            ],
        ),
    ]
