# Generated by Django 4.1.7 on 2023-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registeration',
            name='username',
            field=models.TextField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
