# Generated by Django 4.1.7 on 2023-05-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_result_id_alter_result_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='email',
            field=models.EmailField(default='non', max_length=254),
        ),
        migrations.AddField(
            model_name='registeration',
            name='password1',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='registeration',
            name='password2',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
