# Generated by Django 4.1.7 on 2023-05-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_registeration_email_registeration_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='country',
            field=models.TextField(max_length=100),
        ),
    ]
